apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-tailscale-route
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "60"
spec:
  project: default
  source:
    repoURL: https://github.com/hmk/argocd-test-cluster-config.git
    targetRevision: main
    path: apps/argocd-tailscale-route
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true