apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: onepassword-test
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/hmk/argocd-test-cluster-config.git
    targetRevision: main
    path: apps/onepassword-test

  destination:
    server: https://kubernetes.default.svc
    namespace: onepassword-test

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true